modLoader = "javafml"
loaderVersion = "[1,)"
license = "All Rights Reserved"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = ""
authors = "${mod_authors}"
description = ""

[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "[1.21, 1.22)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "neoforge"
type="required"
versionRange = "[21.0.140-beta,)"
ordering = "NONE"
side = "BOTH"